name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup version from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} --no-restore
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: |
        dotnet pack src/EasySourcing/EasySourcing.csproj --configuration Release /p:Version=${VERSION} --no-build --output output
        dotnet pack src/EasySourcing.EntityFrameworkCore/EasySourcing.EntityFrameworkCore.csproj --configuration Release /p:Version=${VERSION} --no-build --output output
    - name: Push to NuGet
      run: dotnet nuget push **/output/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY} --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
